# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    app.notifier.contact.sendFrom:  support@healthy-food.com
    app.notifier.contact.sendName:  'Healthy Food'

services:
    app.notifier.emailqueue:
          class: AppBundle\Notifier\EmailQueue
          arguments: ['@mailer']

    app.notifier.remind_eating:
          class:      AppBundle\Notifier\RemindEating
          arguments:  ['@app.builder.email', '@app.notifier.emailqueue']

    app.helper.import_data_by_url:
          class:      AppBundle\Helper\ImportDataByUrl
          arguments:  ['@request_stack', '@doctrine.orm.entity_manager']

    app.helper.remind_meal:
          class:      AppBundle\Helper\RemindMeal
          arguments:  ['@doctrine.orm.entity_manager']

    app.helper.notification_helper:
          class:      AppBundle\Helper\NotificationHelper
          arguments:  ['@doctrine.orm.entity_manager']

    app.builder.email:
          class: AppBundle\Builder\EmailBuilder
          scope: prototype
          arguments: ['@twig', '%app.notifier.contact.sendFrom%', '%app.notifier.contact.sendName%']